- name: disable selinux
  selinux: state=disabled

- name: install epel
  yum: name=epel-release state=present disable_gpg_check=yes

- name: install utility programs
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - wget
      - ntp
      - screen
      - epel-release
      - vim
      - ncurses-term
      - gcc
      - make
      - patch
      - python36-devel
      - python36
      - python36-pip
      - kernel-devel
      - kernel-headers
      - jq
      - lvm2
      - yum-utils
      - device-mapper-persistent-data
      - dkms
      - elfutils-libelf-devel
      - qt5-qtx11extras
      - libffi-devel
      - openssl-devel
      - git
      - docker

- name: upgrade kernels
  yum: name={{ packages }} state=latest disable_gpg_check=yes
  vars:
    packages:
      - kernel
      - kernel-devel
      - kernel-headers
  register: kernel

- name: reboot if updated
  reboot:
  when: kernel.changed

- name: install vagrant
  yum: name=https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.rpm state=present disable_gpg_check=yes

- name: install virtualbox 5.1.18 which is used by the DCOS boxes
  yum: name=https://download.virtualbox.org/virtualbox/5.1.18/VirtualBox-5.1-5.1.18_114002_el7-1.x86_64.rpm state=present disable_gpg_check=yes

- name: enable docker and ntp services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - docker
    - ntpd
    - vboxdrv
  register: services

- name: install vagrant vbguest plugin
  command: vagrant plugin install vagrant-vbguest

- name: download extensions
  get_url:
    url: https://download.virtualbox.org/virtualbox/5.1.18/Oracle_VM_VirtualBox_Extension_Pack-5.1.18-114002.vbox-extpack
    dest: /root/Oracle_VM_VirtualBox_Extension_Pack-5.1.18-114002.vbox-extpack
    mode: '0644'
  register: downloadedext

- name: install vbox extentions
  shell: yes | vboxmanage extpack install /root/Oracle_VM_VirtualBox_Extension_Pack-5.1.18-114002.vbox-extpack
  when: downloadedext.changed

- name: reboot if vbox was installed
  reboot:
  when: services.changed

- name: install dcos-e2e (this may take a while)
  command: pip3 install --upgrade git+https://github.com/dcos/dcos-e2e.git@2019.06.19.0

- name: install minidcos
  get_url:
    url: https://github.com/dcos/dcos-e2e/releases/download/2019.06.19.0/minidcos
    dest: /usr/bin/minidcos
    mode: '0755'

- name: downalod dcos installer
  command: minidcos vagrant download-installer

- name: create dcos cluster. see global_vars.yml for settings
  command: minidcos vagrant create ./dcos_generate_config.sh --masters={{ masters }} --public-agents={{ public_agents }} --agents={{ agents }} --vm-memory-mb={{ vmmemory }}

